name: asair_mfc_app
description: ASAir Hardware Controller for Android OTG.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # THE FIX: Bumping the library to the modern Android 14-compliant version
  usb_serial: ^0.5.2

flutter:
  uses-material-design: true
